use std::{fmt::Write as _, fs, process};

use linkage_blaze_mocap::{bvh_frame_params, discover_bvh_parameters, parse_bvh};

const DOF: usize = 132;
const INPUT_PATH: &str = "crates/linkage-blaze-mocap/samples/pirouette.bvh";
const OUTPUT_PATH: &str = "crates/linkage-blaze-ballet/src/ballet_frames_precomputed.rs";

fn main() {
    if let Err(error) = run() {
        eprintln!("{error}");
        process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let source = fs::read_to_string(INPUT_PATH)
        .map_err(|error| format!("failed to read `{INPUT_PATH}`: {error}"))?;
    let clip = parse_bvh(&source).map_err(|error| format!("failed to parse BVH: {error}"))?;
    let layout = discover_bvh_parameters(&clip)
        .map_err(|error| format!("failed to discover BVH params: {error}"))?;

    if layout.len() != DOF {
        return Err(format!("BVH has {} params, expected {DOF}", layout.len()));
    }

    let mut output = String::new();
    writeln!(
        output,
        "// Generated by `just generate-ballet`; included by ballet_frames.rs when the"
    )
    .map_err(format_error)?;
    writeln!(
        output,
        "// `const-parse` feature is not enabled.  Regenerate with `just generate-ballet`."
    )
    .map_err(format_error)?;
    // DOF and FRAME_COUNT are defined in lib.rs; do not duplicate them.
    writeln!(
        output,
        "\npub static FRAMES: [[f32; DOF]; FRAME_COUNT] = ["
    )
    .map_err(format_error)?;

    for frame in &clip.frames {
        let params = bvh_frame_params::<DOF>(&layout, frame)
            .map_err(|error| format!("failed to convert BVH frame: {error}"))?;
        output.push_str("    [");
        for (param_index, param) in params.iter().enumerate() {
            if param_index > 0 {
                output.push_str(", ");
            }
            write!(output, "{param:?}").map_err(format_error)?;
        }
        output.push_str("],\n");
    }
    output.push_str("];\n");

    fs::write(OUTPUT_PATH, output)
        .map_err(|error| format!("failed to write `{OUTPUT_PATH}`: {error}"))?;

    Ok(())
}

fn format_error(error: std::fmt::Error) -> String {
    format!("failed to format generated ballet frames: {error}")
}
