linkage![
    .define_param("x", 0.5)
    .define_param("y", 0.5)
    .define_param("z", 0.5)
    // Fixed printer frame.
    .pen_up()
    .mark("origin")
    .pen_color(Rgb888::CSS_DARK_SLATE_GRAY)
    .pen_width(8.0)
    .pen_down()
    .up(265.0)
    .forward(400.0)
    .up(-265.0)
    .pen_up()
    .restore("origin")
    // Visible Z lift screws beside the fixed uprights.
    .pen_color(Rgb888::CSS_DIM_GRAY)
    .pen_width(3.0)
    .forward(18.0)
    .pen_down()
    .up_param("z", 28.0, 278.0)
    .sphere(4.0)
    .pen_up()
    .restore("origin")
    .forward(382.0)
    .pen_down()
    .up_param("z", 28.0, 278.0)
    .sphere(4.0)
    .pen_up()
    .restore("origin")
    // Lift to the X gantry. The hotend hangs 20 mm below this carriage height.
    .pen_up()
    .up_param("z", 28.0, 278.0)
    .mark("gantry_left")
    // X gantry rod.
    .pen_color(Rgb888::CSS_STEEL_BLUE)
    .pen_width(5.0)
    .pen_down()
    .forward(400.0)
    .pen_up()
    // Moving gantry brackets.
    .pen_color(Rgb888::CSS_DARK_SLATE_GRAY)
    .sphere(7.0)
    .restore("gantry_left")
    .pen_color(Rgb888::CSS_DARK_SLATE_GRAY)
    .sphere(7.0)
    // X carriage and hotend. The nozzle tip is at z_mm.
    .forward_param("x", 90.0, 310.0)
    .mark("carriage")
    .pen_color(Rgb888::CSS_DARK_SLATE_GRAY)
    .sphere(10.0)
    .pen_color(Rgb888::CSS_DIM_GRAY)
    .pen_width(5.0)
    .pen_down()
    .up(-16.0)
    .pen_up()
    .pen_color(Rgb888::CSS_CRIMSON)
    .sphere(3.5)
    .pen_color(Rgb888::CSS_CRIMSON)
    .pen_width(2.0)
    .pen_down()
    .up(-4.0)
    .pen_up()
    .sphere(1.6)
    // Fixed printer base under the moving bed.
    .restore("gantry_left")
    .up_param("z", -28.0, -278.0)
    .forward(200.0)
    .pen_color(Rgb888::CSS_LIGHT_GRAY)
    .disk(205.0)
    .pen_color(Rgb888::CSS_LIGHT_SLATE_GRAY)
    .pen_width(5.0)
    .ring(205.0)
    // Bed-slinger plate. Y moves the bed under the fixed-Y nozzle.
    .restore("gantry_left")
    .up_param("z", -20.0, -270.0)
    .forward(200.0)
    .left_param("y", 120.0, -120.0)
    .mark("bed_center")
    .pen_color(Rgb888::CSS_STEEL_BLUE)
    .pen_width(3.0)
    .pen_down()
    .left(-110.0)
    .sphere(4.0)
    .left(220.0)
    .sphere(4.0)
    .restore("bed_center")
    .pen_color(Rgb888::CSS_STEEL_BLUE)
    .pen_width(3.0)
    .pen_down()
    .forward(-110.0)
    .sphere(4.0)
    .forward(220.0)
    .sphere(4.0)
    .pen_up()
    .pen_color(Rgb888::CSS_STEEL_BLUE)
    .restore("bed_center")
    .pen_color(Rgb888::CSS_STEEL_BLUE)
    .disk(170.0)
]
