[workspace]
members = ["linkage-blaze-core", "linkage-blaze-utils"]
resolver = "3"

[workspace.package]
version = "0.1.5"
edition = "2024"
rust-version = "1.93"
license = "MIT OR Apache-2.0"
repository = "https://github.com/CarlKCarlK/linkage-blaze"
homepage = "https://github.com/CarlKCarlK/linkage-blaze"

