[alias]
xtask = "run -p linkage-blaze-xtask --"
check-all = "run --quiet -p linkage-blaze-xtask -- check-all"

[env]
DEFMT_LOG = "info"

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip=RP2040"
rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "link-arg=--gc-sections",
]

[target.thumbv8m.main-none-eabihf]
runner = "probe-rs run --chip=RP235x"
rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "link-arg=--gc-sections",
]
