// @generated by cargo xtask generate-board-examples.

//! clock_esp32s2_generic: not supported on this board profile.
//!
//! - this example needs a large RAM/linker budget, and ESP32-S2 is stack-constrained

#![no_std]
#![no_main]

use core::{convert::Infallible, future::pending};

use device_envoy_esp::{Result, init_and_start};
use embassy_executor::Spawner;
use esp_backtrace as _;
use log::info;

esp_bootloader_esp_idf::esp_app_desc!();

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(_spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);
    info!(
        "clock_esp32s2_generic: this example needs a large RAM/linker budget, and ESP32-S2 is stack-constrained"
    );
    pending().await
}
