// @generated by cargo xtask generate-board-examples.

//! armatron_one_spi_esp32c2_devkitm1_v1_0: not supported on this board profile.
//!
//! - this board's wiring assigns GPIO3 to more than one of the display bus, touch chip-select/IRQ, and button roles this one-SPI example needs at once

#![no_std]
#![no_main]

use core::{convert::Infallible, future::pending};

use device_envoy_esp::{Result, init_and_start};
use embassy_executor::Spawner;
use esp_backtrace as _;
use log::info;

esp_bootloader_esp_idf::esp_app_desc!();

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(_spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);
    info!(
        "armatron_one_spi_esp32c2_devkitm1_v1_0: this board's wiring assigns GPIO3 to more than one of the display bus, touch chip-select/IRQ, and button roles this one-SPI example needs at once"
    );
    pending().await
}
