use minijinja::{Environment, context};
use std::collections::HashSet;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

#[path = "../../../mcu/device-envoy/crates/device-envoy-esp/xtask/src/boards.rs"]
mod device_envoy_esp_boards;

use device_envoy_esp_boards::{AudioWiring, BOARD_PROFILES, BoardProfile, validate_board_profiles};

const GENERATED_EXAMPLES_BEGIN_MARKER: &str = "# BEGIN GENERATED BOARD EXAMPLES";
const GENERATED_EXAMPLES_END_MARKER: &str = "# END GENERATED BOARD EXAMPLES";
const GENERATED_FILE_HEADER: &str = "// @generated by cargo xtask generate-board-examples.\n";
const LINKAGE_ESP_CRATE_DIR: &str = "crates/linkage-blaze-examples-esp";
const EXAMPLE_FEATURES: &[(&str, &str)] = &[
    ("armatron", "armatron"),
    ("armatron_one_spi", "armatron"),
    ("ballet", "ballet"),
    ("clock", "clock"),
    ("skeleton_clock", "skeleton-clock"),
];

#[derive(Clone, Copy, PartialEq, Eq)]
enum BoardTemplateRequirement {
    Wifi,
    MinSpi(u8),
    LargeStack,
    /// The board's `cyd_display_wiring`, `cyd_touch_wiring.{cs,irq}`, and
    /// `button_pin` must all be distinct GPIOs, since a one-SPI CYD example
    /// wires up display, touch chip-select/IRQ, and the button all at once.
    NoCydOneSpiPinConflict,
}

struct BoardTemplateSpec {
    requirements: Vec<BoardTemplateRequirement>,
}

pub fn generate_board_examples(workspace_root: &Path) -> Result<(), Box<dyn Error>> {
    validate_board_profiles()?;
    verify_imported_board_schema_is_fully_referenced();

    let crate_root = workspace_root.join(LINKAGE_ESP_CRATE_DIR);
    let examples_dir = crate_root.join("examples");
    let templates_dir = examples_dir.join("templates");
    let template_base_names = discover_template_base_names(&templates_dir)?;
    let expected_paths = generate_example_sources(&examples_dir, &template_base_names)?;
    rustfmt_generated_files(&expected_paths)?;
    cleanup_stale_generated_examples(&examples_dir, &expected_paths)?;
    sync_generated_examples_in_cargo_toml(&crate_root, &template_base_names)?;
    Ok(())
}

/// Target triple and Xtensa linker name for a `device-envoy-esp` chip feature, or `None`
/// for RISC-V chips that build with plain stable `cargo build` (no Xtensa toolchain needed).
///
/// Xtensa chips (`esp32`, `esp32s2`, `esp32s3`) build with the `esp` toolchain and
/// `-Zbuild-std=core,alloc`, since the `esp` toolchain ships no prebuilt Xtensa sysroot.
fn build_target_for_chip_feature(chip_feature: &str) -> (&'static str, Option<&'static str>) {
    match chip_feature {
        "esp32" => ("xtensa-esp32-none-elf", Some("xtensa-esp32-elf-gcc")),
        "esp32c2" | "esp32c3" => ("riscv32imc-unknown-none-elf", None),
        "esp32c5" | "esp32c6" | "esp32c61" | "esp32h2" => ("riscv32imac-unknown-none-elf", None),
        "esp32s2" => ("xtensa-esp32s2-none-elf", Some("xtensa-esp32s2-elf-gcc")),
        "esp32s3" => ("xtensa-esp32s3-none-elf", Some("xtensa-esp32s3-elf-gcc")),
        other => panic!("unknown device-envoy-esp chip feature: {other}"),
    }
}

/// Locates the requested Xtensa linker and returns its parent directory, or `None` when it
/// is already on `PATH`. `espup install` places these under `~/.rustup/toolchains/esp/`.
fn find_xtensa_linker_dir(linker: &str) -> Option<PathBuf> {
    if Command::new(linker)
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .output()
        .map(|output| output.status.success())
        .unwrap_or(false)
    {
        return None;
    }

    let home = std::env::var_os("HOME").unwrap_or_default();
    let esp_toolchain = Path::new(&home).join(".rustup/toolchains/esp");

    fn find_in(dir: &Path, linker: &str, depth: u32) -> Option<PathBuf> {
        if depth == 0 {
            return None;
        }
        let Ok(entries) = std::fs::read_dir(dir) else {
            return None;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                if path.join(linker).exists() {
                    return Some(path);
                }
                if let Some(found) = find_in(&path, linker, depth - 1) {
                    return Some(found);
                }
            }
        }
        None
    }

    find_in(&esp_toolchain, linker, 6)
}

/// Prepends `dir` to the `PATH` environment variable for `command`.
fn prepend_path(command: &mut Command, dir: &Path) {
    let current = std::env::var_os("PATH").unwrap_or_default();
    let mut paths = std::env::split_paths(&current).collect::<Vec<_>>();
    paths.insert(0, dir.to_owned());
    command.env(
        "PATH",
        std::env::join_paths(paths).expect("PATH join failed"),
    );
}

/// Builds every generated `linkage-blaze-examples-esp` board example (real or placeholder) for its
/// own board's target, so `just check-all` exercises the full board matrix instead of a
/// hand-picked handful of `esp32_generic` examples.
pub fn build_all_board_examples(workspace_root: &Path) -> Result<(), Box<dyn Error>> {
    let crate_root = workspace_root.join(LINKAGE_ESP_CRATE_DIR);
    let templates_dir = crate_root.join("examples").join("templates");
    let template_base_names = discover_template_base_names(&templates_dir)?;

    for board_profile in BOARD_PROFILES {
        let (target, xtensa_linker) = build_target_for_chip_feature(board_profile.chip_feature());
        let xtensa_linker_dir = xtensa_linker.and_then(find_xtensa_linker_dir);
        for base_name in &template_base_names {
            let example_name = board_example_name(*board_profile, base_name);
            let example_feature = example_feature_name(base_name)
                .unwrap_or_else(|| panic!("missing example feature mapping for {base_name}"));
            println!("    build example: {example_name}");

            let mut command = Command::new("cargo");
            command.current_dir(&crate_root);
            if let Some(dir) = &xtensa_linker_dir {
                prepend_path(&mut command, dir);
            }
            if xtensa_linker.is_some() {
                command.arg("+esp");
            }
            command.args(["build", "--example", &example_name, "--release"]);
            command.args(["--target", target]);
            command.args(["--no-default-features", "--features"]);
            command.arg(format!(
                "{},{example_feature}",
                board_profile.chip_feature()
            ));
            if xtensa_linker.is_some() {
                command.arg("-Zbuild-std=core,alloc");
            }
            // `ballet`'s embedded `MOTION` capture is a heavy const; the generated source
            // already carries `#![allow(long_running_const_eval)]`, but -D warnings at the
            // command line has tripped over it historically, so belt-and-suspenders here too.
            let rustflags = if example_feature == "ballet" {
                "-D warnings -C link-arg=-Tlinkall.x -A long-running-const-eval"
            } else {
                "-D warnings -C link-arg=-Tlinkall.x"
            };
            command.env("RUSTFLAGS", rustflags);

            let status = command.status()?;
            if !status.success() {
                return Err(format!("cargo build failed for example {example_name}").into());
            }
        }
    }
    Ok(())
}

fn verify_imported_board_schema_is_fully_referenced() {
    for board_profile in BOARD_PROFILES {
        std::hint::black_box(
            u32::from(board_profile.rmt_count)
                + u32::from(board_profile.built_in_plain_led.unwrap_or_default())
                + u32::from(board_profile.led_strip_len_8_pin)
                + u32::from(board_profile.led_2d12x8_pin)
                + u32::from(board_profile.led_2d16x16_pin)
                + u32::from(board_profile.lcd_sda_pin)
                + u32::from(board_profile.lcd_scl_pin)
                + u32::from(board_profile.servo_pin)
                + u32::from(board_profile.servo2_pin)
                + u32::from(board_profile.led4_cell_pins[0])
                + u32::from(board_profile.led4_segment_pins[0])
                + u32::from(board_profile.rfid_wiring.sck_pin_num)
                + u32::from(board_profile.rfid_wiring.mosi_pin_num)
                + u32::from(board_profile.rfid_wiring.miso_pin_num)
                + u32::from(board_profile.rfid_wiring.cs_pin_num)
                + u32::from(board_profile.rfid_wiring.rst_pin_num)
                + board_profile.unavailable_gpios.len() as u32,
        );
        std::hint::black_box(
            board_profile
                .audio_wiring
                .map(|audio_wiring| {
                    u32::from(audio_wiring.data_pin_num)
                        + u32::from(audio_wiring.bit_clock_pin_num)
                        + u32::from(audio_wiring.word_select_pin_num)
                        + audio_wiring.dma_identifier.len() as u32
                })
                .unwrap_or_default(),
        );
    }
}

fn discover_template_base_names(templates_dir: &Path) -> Result<Vec<String>, Box<dyn Error>> {
    let mut base_names = Vec::new();
    for template_entry in fs::read_dir(templates_dir)? {
        let template_entry = template_entry?;
        let template_path = template_entry.path();
        if !template_path.is_file() {
            continue;
        }
        let Some(relative_name) = template_path
            .file_name()
            .and_then(|file_name| file_name.to_str())
        else {
            continue;
        };
        let Some(base_name) = relative_name.strip_suffix(".rs.j2") else {
            continue;
        };
        base_names.push(base_name.to_string());
    }
    base_names.sort();
    Ok(base_names)
}

fn generate_example_sources(
    examples_dir: &Path,
    template_base_names: &[String],
) -> Result<Vec<PathBuf>, Box<dyn Error>> {
    let mut expected_paths = Vec::new();
    for base_name in template_base_names {
        let template_path = examples_dir
            .join("templates")
            .join(format!("{base_name}.rs.j2"));
        let template_source = fs::read_to_string(&template_path)?;
        let template_spec = parse_board_template_spec(&template_source)?;
        let template_body = strip_board_template_header(&template_source);
        for board_profile in BOARD_PROFILES {
            let output_path = examples_dir
                .join(board_profile.chip_dir())
                .join(board_profile.board_dir())
                .join(format!("{base_name}.rs"));
            if let Some(output_dir) = output_path.parent() {
                fs::create_dir_all(output_dir)?;
            }
            let generated_source = if board_template_supports_board(&template_spec, *board_profile)
            {
                render_supported_template(base_name, &template_body, *board_profile)?
            } else {
                render_placeholder_source(base_name, &template_spec, *board_profile)
            };
            fs::write(&output_path, generated_source)?;
            expected_paths.push(output_path);
        }
    }
    Ok(expected_paths)
}

fn render_supported_template(
    base_name: &str,
    template_body: &str,
    board_profile: BoardProfile,
) -> Result<String, Box<dyn Error>> {
    let mut minijinja_environment = Environment::new();
    minijinja_environment.add_template(base_name, template_body)?;
    let audio_wiring = board_profile.audio_wiring.unwrap_or(AudioWiring {
        data_pin_num: u8::MAX,
        bit_clock_pin_num: u8::MAX,
        word_select_pin_num: u8::MAX,
        dma_identifier: "DMA_UNSUPPORTED_AUDIO",
    });
    Ok(minijinja_environment
        .get_template(base_name)?
        .render(context! {
            example_name => board_example_name(board_profile, base_name),
            chip_name => board_profile.chip_name(),
            chip_feature => board_profile.chip_feature(),
            board_slug => board_profile.board_slug(),
            button_pin => board_profile.button_pin,
            clock_supported => board_profile.wifi_supported,
            cyd_display_sck_pin => board_profile.cyd_display_wiring.sck_pin_num,
            cyd_display_mosi_pin => board_profile.cyd_display_wiring.mosi_pin_num,
            cyd_display_miso_pin => board_profile.cyd_display_wiring.miso_pin_num,
            cyd_display_cs_pin => board_profile.cyd_display_wiring.cs_pin_num,
            cyd_display_dc_pin => board_profile.cyd_display_wiring.dc_pin_num,
            cyd_display_rst_pin => board_profile.cyd_display_wiring.rst_pin_num,
            cyd_display_backlight_pin => board_profile.cyd_display_wiring.backlight_pin_num,
            cyd_touch_sck_pin => board_profile.cyd_touch_wiring.sck_pin_num,
            cyd_touch_mosi_pin => board_profile.cyd_touch_wiring.mosi_pin_num,
            cyd_touch_miso_pin => board_profile.cyd_touch_wiring.miso_pin_num,
            cyd_touch_cs_pin => board_profile.cyd_touch_wiring.cs_pin_num,
            cyd_touch_irq_pin => board_profile.cyd_touch_wiring.irq_pin_num,
            audio_data_pin => audio_wiring.data_pin_num,
            audio_bit_clock_pin => audio_wiring.bit_clock_pin_num,
            audio_word_select_pin => audio_wiring.word_select_pin_num,
            audio_dma_identifier => audio_wiring.dma_identifier,
        })?)
}

fn parse_board_template_spec(template_source: &str) -> Result<BoardTemplateSpec, Box<dyn Error>> {
    let Some(template_line) = template_source.lines().next() else {
        return Err("missing @board-example template header".into());
    };
    let Some(spec_fragment) = template_line.split("@board-example").nth(1) else {
        return Err("missing @board-example template header".into());
    };
    let spec_text = spec_fragment
        .trim()
        .trim_end_matches("#}")
        .trim_end_matches("*/")
        .trim();
    let mut requirements = Vec::new();
    for token in spec_text.split_whitespace() {
        let requirement = if token == "wifi" {
            BoardTemplateRequirement::Wifi
        } else if let Some(count) = token.strip_prefix("min_spi=") {
            BoardTemplateRequirement::MinSpi(count.parse()?)
        } else if token == "large_stack" {
            BoardTemplateRequirement::LargeStack
        } else if token == "no_cyd_one_spi_pin_conflict" {
            BoardTemplateRequirement::NoCydOneSpiPinConflict
        } else {
            return Err(format!(
                "invalid @board-example requirement `{token}` (expected `wifi`, `min_spi=<n>`, `large_stack`, or `no_cyd_one_spi_pin_conflict`)"
            )
            .into());
        };
        requirements.push(requirement);
    }
    Ok(BoardTemplateSpec { requirements })
}

fn strip_board_template_header(template_source: &str) -> String {
    let mut lines = template_source.lines();
    let _template_header = lines.next();
    let remainder = lines.collect::<Vec<_>>().join("\n");
    if template_source.ends_with('\n') {
        format!("{remainder}\n")
    } else {
        remainder
    }
}

fn board_template_supports_board(
    template_spec: &BoardTemplateSpec,
    board_profile: BoardProfile,
) -> bool {
    template_spec
        .requirements
        .iter()
        .copied()
        .all(|requirement| board_requirement_supported(requirement, board_profile))
}

fn board_requirement_supported(
    requirement: BoardTemplateRequirement,
    board_profile: BoardProfile,
) -> bool {
    match requirement {
        BoardTemplateRequirement::Wifi => board_profile.wifi_supported,
        BoardTemplateRequirement::MinSpi(count) => board_profile.spi_count >= count,
        BoardTemplateRequirement::LargeStack => !board_profile.stack_constrained,
        BoardTemplateRequirement::NoCydOneSpiPinConflict => {
            cyd_one_spi_conflicting_pin(board_profile).is_none()
        }
    }
}

/// The GPIO number used by more than one role in a one-SPI CYD example (display bus/CS/DC/RST/
/// backlight, touch CS/IRQ, and the calibration button all wired up at once), if any.
///
/// Two-SPI boards never surface this because their display and touch peripherals are
/// independent; a one-SPI example shares one bus and so needs every one of these roles to land
/// on a distinct GPIO.
fn cyd_one_spi_conflicting_pin(board_profile: BoardProfile) -> Option<u8> {
    let display = board_profile.cyd_display_wiring;
    let touch = board_profile.cyd_touch_wiring;
    let pins = [
        display.sck_pin_num,
        display.mosi_pin_num,
        display.miso_pin_num,
        display.cs_pin_num,
        display.dc_pin_num,
        display.rst_pin_num,
        display.backlight_pin_num,
        touch.cs_pin_num,
        touch.irq_pin_num,
        board_profile.button_pin,
    ];
    for (index, &pin) in pins.iter().enumerate() {
        if pins[..index].contains(&pin) {
            return Some(pin);
        }
    }
    None
}

fn render_placeholder_source(
    base_name: &str,
    template_spec: &BoardTemplateSpec,
    board_profile: BoardProfile,
) -> String {
    let reason = placeholder_reason(template_spec, board_profile)
        .unwrap_or_else(|| "this board profile is unsupported for this example".to_string());
    let example_name = board_example_name(board_profile, base_name);
    format!(
        "{GENERATED_FILE_HEADER}\n\
//! {example_name}: not supported on this board profile.\n\
//!\n\
//! - {reason}\n\
\n\
#![no_std]\n\
#![no_main]\n\
\n\
use core::{{convert::Infallible, future::pending}};\n\
\n\
use device_envoy_esp::{{Result, init_and_start}};\n\
use embassy_executor::Spawner;\n\
use esp_backtrace as _;\n\
use log::info;\n\
\n\
esp_bootloader_esp_idf::esp_app_desc!();\n\
\n\
#[esp_rtos::main]\n\
async fn main(spawner: Spawner) -> ! {{\n\
    let err = inner_main(spawner).await.unwrap_err();\n\
    panic!(\"{{err:?}}\");\n\
}}\n\
\n\
async fn inner_main(_spawner: Spawner) -> Result<Infallible> {{\n\
    init_and_start!(p);\n\
    esp_println::logger::init_logger(log::LevelFilter::Info);\n\
    info!(\"{example_name}: {reason}\");\n\
    pending().await\n\
}}\n"
    )
}

fn placeholder_reason(
    template_spec: &BoardTemplateSpec,
    board_profile: BoardProfile,
) -> Option<String> {
    for requirement in &template_spec.requirements {
        if board_requirement_supported(*requirement, board_profile) {
            continue;
        }
        return Some(match requirement {
            BoardTemplateRequirement::Wifi => format!(
                "this example requires Wi-Fi, and {} does not offer that resource",
                board_profile.chip_name()
            ),
            BoardTemplateRequirement::MinSpi(count) => format!(
                "this example requires {count} SPI resources, and {} offers {} SPI {}",
                board_profile.chip_name(),
                board_profile.spi_count,
                if board_profile.spi_count == 1 {
                    "resource"
                } else {
                    "resources"
                }
            ),
            BoardTemplateRequirement::LargeStack => format!(
                "this example needs a large RAM/linker budget, and {} is stack-constrained",
                board_profile.chip_name()
            ),
            BoardTemplateRequirement::NoCydOneSpiPinConflict => format!(
                "this board's wiring assigns GPIO{} to more than one of the display bus, \
                 touch chip-select/IRQ, and button roles this one-SPI example needs at once",
                cyd_one_spi_conflicting_pin(board_profile)
                    .expect("requirement only fails when a conflicting pin exists")
            ),
        });
    }
    None
}

fn board_example_name(board_profile: BoardProfile, base_name: &str) -> String {
    format!(
        "{}_{}_{}",
        base_name,
        board_profile.chip_feature(),
        board_profile.board_dir()
    )
}

fn sync_generated_examples_in_cargo_toml(
    crate_root: &Path,
    template_base_names: &[String],
) -> Result<(), Box<dyn Error>> {
    let cargo_toml_path = crate_root.join("Cargo.toml");
    let cargo_toml_source = fs::read_to_string(&cargo_toml_path)?;
    let generated_block = render_generated_examples_block(template_base_names);
    let begin_index = cargo_toml_source
        .find(GENERATED_EXAMPLES_BEGIN_MARKER)
        .ok_or("Cargo.toml missing generated examples begin marker")?;
    let end_index = cargo_toml_source
        .find(GENERATED_EXAMPLES_END_MARKER)
        .ok_or("Cargo.toml missing generated examples end marker")?;
    let block_end = end_index + GENERATED_EXAMPLES_END_MARKER.len();
    let trailing_newline_len = cargo_toml_source[block_end..]
        .chars()
        .next()
        .is_some_and(|character| character == '\n') as usize;
    let remove_end = block_end + trailing_newline_len;
    let mut rewritten = String::with_capacity(cargo_toml_source.len() + generated_block.len());
    rewritten.push_str(&cargo_toml_source[..begin_index]);
    rewritten.push_str(&generated_block);
    rewritten.push_str(&cargo_toml_source[remove_end..]);
    write_if_changed(&cargo_toml_path, &rewritten)?;
    Ok(())
}

fn render_generated_examples_block(template_base_names: &[String]) -> String {
    let mut block = String::new();
    block.push_str(GENERATED_EXAMPLES_BEGIN_MARKER);
    block.push('\n');
    for board_profile in BOARD_PROFILES {
        for base_name in template_base_names {
            let example_feature = example_feature_name(base_name)
                .unwrap_or_else(|| panic!("missing example feature mapping for {base_name}"));
            block.push_str("[[example]]\n");
            block.push_str(&format!(
                "name = \"{}\"\n",
                board_example_name(*board_profile, base_name)
            ));
            block.push_str(&format!(
                "path = \"examples/{}/{}/{}.rs\"\n",
                board_profile.chip_dir(),
                board_profile.board_dir(),
                base_name
            ));
            block.push_str(&format!(
                "required-features = [\"{}\", \"{}\"]\n\n",
                board_profile.chip_feature(),
                example_feature
            ));
        }
    }
    block.push_str(GENERATED_EXAMPLES_END_MARKER);
    block.push('\n');
    block
}

fn example_feature_name(base_name: &str) -> Option<&'static str> {
    EXAMPLE_FEATURES
        .iter()
        .find_map(|(template_name, feature_name)| {
            (*template_name == base_name).then_some(*feature_name)
        })
}

fn cleanup_stale_generated_examples(
    examples_dir: &Path,
    expected_paths: &[PathBuf],
) -> Result<(), Box<dyn Error>> {
    let expected_paths: HashSet<PathBuf> = expected_paths.iter().cloned().collect();
    for board_profile in BOARD_PROFILES {
        let board_dir = examples_dir
            .join(board_profile.chip_dir())
            .join(board_profile.board_dir());
        if !board_dir.exists() {
            continue;
        }
        for candidate_entry in fs::read_dir(&board_dir)? {
            let candidate_entry = candidate_entry?;
            let candidate_path = candidate_entry.path();
            if !candidate_path.is_file() || expected_paths.contains(&candidate_path) {
                continue;
            }
            let existing = fs::read_to_string(&candidate_path)?;
            if existing.starts_with(GENERATED_FILE_HEADER) {
                fs::remove_file(candidate_path)?;
            }
        }
    }
    Ok(())
}

fn rustfmt_generated_files(paths: &[PathBuf]) -> Result<(), Box<dyn Error>> {
    if paths.is_empty() {
        return Ok(());
    }
    let mut rustfmt_command = Command::new("rustfmt");
    rustfmt_command.arg("--edition").arg("2024");
    for path in paths {
        rustfmt_command.arg(path);
    }
    let rustfmt_status = rustfmt_command.status()?;
    if rustfmt_status.success() {
        Ok(())
    } else {
        Err("rustfmt failed for generated linkage-blaze-examples-esp examples".into())
    }
}

fn write_if_changed(path: &Path, contents: &str) -> Result<(), Box<dyn Error>> {
    match fs::read_to_string(path) {
        Ok(existing) if existing == contents => Ok(()),
        _ => {
            fs::write(path, contents)?;
            Ok(())
        }
    }
}
