// todo00000 robot arm linkage 1
          Linkage::start()
        .define_param("raise hand", 0.5)
        .define_param("bend elbow", 0.5)
        .define_param("close hand", 0.5)
        .define_param("lower arm", 0.5)
        .define_param("spin whole arm", 0.5)
        .define_param("spin hand", 0.5)
        .yaw_param("spin whole arm", 180.0, -180.0)
        .pen_color(Rgb888::CSS_DARK_CYAN)
        .pen_width(0.15)
        .up(2.5)
        .pitch_param("lower arm", -30.0, 0.0)
        .forward(3.0)
        .yaw_param("bend elbow", 90.0, -90.0)
        .forward(3.0)
        .pitch_param("raise hand", 90.0, -90.0)
        .forward(1.0)
        .roll_param("spin hand", -180.0, 180.0)
        .forward(0.5)
        .remember("wrist")
        .yaw(90.0)
        .forward_param("close hand", 0.5, 0.0)
        .left(-1.0)
   .recall("wrist")
        .yaw(-90.0)
        .forward_param("close hand", 0.5, 0.0)
        .left(1.0)
