Linkage::start()
    .define_param("x/y view", 0.5833)
    .define_param("z", 0.8333)
    .define_param("raise hand", 0.5)
    .define_param("bend elbow", 0.5)
    .define_param("close hand", 0.0)
    .define_param("lower arm", 0.5)
    .define_param("spin whole", 0.5)
    .define_param("spin hand", 0.5)
    .define_param("target yaw 0", 0.5)
    .define_param("target pitch 1", 0.5)
    .define_param("target yaw 2", 0.5)
    .define_param("target pitch 3", 0.5)
    .define_param("target yaw 4", 0.5)
    .define_param("target roll 5", 0.5)
    // ---- floor ----
    // .pitch_param(BASE_PITCH_PARAM, -45.0, 45.0)
    // .yaw_param(BASE_YAW_PARAM, -180.0, 180.0)
    // .pen_color(FLOOR_COLOR)
    // .disk(FLOOR_RADIUS)
    // .pen_color(AXIS_COLOR)
    // .pen_width(AXIS_WIDTH)
    // // x-axis half-line (forward direction)
    // .forward(AXIS_RADIUS)
    // .pen_up()
    // .yaw(180.0)
    // .forward(AXIS_RADIUS) // silently return to origin
    // .yaw(90.0) // now facing +col1 (y axis)
    // .pen_down()
    // .forward(AXIS_RADIUS)
    // .restart()
    // ---- arm ----
    .pen_color(Rgb888::CSS_DARK_GREEN)
    .pen_width(3.0)
    .yaw(90.0)
    .pitch(-90.0)
    .yaw_param("x/y view", 90.0, -90.0)
    .pitch_param("z", -45.0, 45.0)
    .yaw_param("spin whole", 360.0, -360.0)
    .pitch(90.0)
    .forward(2.5)
    .pitch(-90.0)
    .pitch_param("lower arm", 30.0, 0.0)
    .forward(3.0)
    .yaw_param("bend elbow", 90.0, -90.0)
    .forward(3.0)
    .pitch_param("raise hand", 90.0, -90.0)
    .forward(1.0)
    .roll_param("spin hand", -360.0, 360.0)
    .forward(0.5)
    .yaw(90.0)
    .forward_param("close hand", 0.5, 0.0)
    .yaw(-90.0)
    .forward(1.0)
    .yaw(180.0)
    .forward(1.0)
    .yaw(90.0)
    .forward_param("close hand", 1.0, 0.0)
    .yaw(90.0)
    .forward(1.0)
    // // ---- target (pen up: no arm strokes, only the disk at the end) ----
    // .pen_up()
    // .pitch_param(BASE_PITCH_PARAM, -45.0, 45.0)
    // .yaw_param(BASE_YAW_PARAM, -180.0, 180.0)
    // .pen_color(TARGET_COLOR)
    // .yaw(90.0)
    // .yaw_param("spin whole", 360.0, -360.0)
    // .pitch(90.0)
    // .forward(2.5)
    // .pitch(-90.0)
    // .pitch_param("lower arm", 30.0, 0.0)
    // .forward(3.0)
    // .yaw_param("bend elbow", 90.0, -90.0)
    // .forward(3.0)
    // .pitch_param("raise hand", 90.0, -90.0)
    // .forward(1.0)
    // .roll_param("spin hand", -360.0, 360.0)
    // .forward(0.5)
    // .yaw(90.0)
    // .forward_param("close hand", 0.5, 0.0)
    // .yaw(-90.0)
    // .forward(1.0)
    // .yaw(180.0)
    // .forward(1.0)
    // .yaw(90.0)
    // .forward_param("close hand", 1.0, 0.0)
    // .yaw(90.0)
    // .forward(1.0)
    // // 6 random extension joints → target position
    // .yaw_param(TARGET_PARAM_START, -180.0, 180.0)
    // .forward(2.0)
    // .pitch_param(TARGET_PARAM_START + 1, -60.0, 60.0)
    // .forward(2.0)
    // .yaw_param(TARGET_PARAM_START + 2, -180.0, 180.0)
    // .forward(2.0)
    // .pitch_param(TARGET_PARAM_START + 3, -60.0, 60.0)
    // .forward(2.0)
    // .yaw_param(TARGET_PARAM_START + 4, -180.0, 180.0)
    // .forward(2.0)
    // .roll_param(TARGET_PARAM_START + 5, -180.0, 180.0)
    // .forward(2.0)
    // .disk_param("close hand", TARGET_MIN_RADIUS, TARGET_MAX_RADIUS)
