Linkage::start().pen_color(Rgb888::CSS_DARK_SLATE_GRAY)
    .mark("origin")
    // Horizontal lines: snake along forward, step left
    .pen_up().left(-4.0).forward(-4.0)
    .pen_down().forward(8.0)
    .pen_up().left(1.0).pen_down().forward(-8.0)
    .pen_up().left(1.0).pen_down().forward(8.0)
    .pen_up().left(1.0).pen_down().forward(-8.0)
    .pen_up().left(1.0).pen_down().forward(8.0)
    .pen_up().left(1.0).pen_down().forward(-8.0)
    .pen_up().left(1.0).pen_down().forward(8.0)
    .pen_up().left(1.0).pen_down().forward(-8.0)
    .pen_up().left(1.0).pen_down().forward(8.0)
    .pen_up()
    .restore("origin")
    // Vertical lines: snake along left, step forward
    .pen_up().forward(-4.0).left(-4.0)
    .pen_down().left(8.0)
    .pen_up().forward(1.0).pen_down().left(-8.0)
    .pen_up().forward(1.0).pen_down().left(8.0)
    .pen_up().forward(1.0).pen_down().left(-8.0)
    .pen_up().forward(1.0).pen_down().left(8.0)
    .pen_up().forward(1.0).pen_down().left(-8.0)
    .pen_up().forward(1.0).pen_down().left(8.0)
    .pen_up().forward(1.0).pen_down().left(-8.0)
    .pen_up().forward(1.0).pen_down().left(8.0)
    .pen_up()
    .restore("origin")
